= 拓展
:page-toclevels: 1

`Neutralino.extensions` 命名空间包含与 Neutralino 扩展相关的方法。扩展允许开发人员为 Neutralinojs 应用程序编写自定义后端 API。

通过这个 xref:how-to/extensions-overview.adoc[指南] 了解更多关于扩展的信息。

[[extensionsdispatchextensionid-eventname-data]]
== 分发事件

`extensions.dispatch(extensionId, eventName, data)`

向扩展实例分发一个新的事件。如果目标扩展尚未连接，Neutralino 客户端库将把函数调用放入队列，并在扩展上线时发送。

[[parameters]]
=== 参数

* `extensionId` String：扩展标识符。
* `eventName` String：事件的名称。
* `data` Object（可选）：事件的额外数据。

[source,javascript]
----
await Neutralino.extensions.dispatch('js.neutralino.sampleextension',
            'myTestEvent', {myData: 'Test data'});

await Neutralino.extensions.dispatch('js.neutralino.sampleextension',
            'myTestEvent');
----

[[extensionsbroadcasteventname-data]]
== 广播事件

`extensions.broadcast(eventName, data)`

向所有已连接的扩展分发一个新的事件。如果扩展已加载但尚未连接，该特定扩展将不会收到新事件。即使扩展尚未连接到主进程，也可以使用 xref:api/extensions.adoc#extensionsdispatchextensionid-eventname-data[extensions.dispatch] 发送消息。

[[parameters-1]]
=== 参数

* `eventName` String：事件的名称。
* `data` Object（可选）：事件的额外数据。

[source,javascript]
----
await Neutralino.extensions.broadcast('myTestEvent', 'Hello');

await Neutralino.extensions.broadcast('myTestEvent', {myData: 'Test data'});

await Neutralino.extensions.broadcast('myTestEvent');
----

[[extensionsgetstats]]
== 获取详细信息

`extensions.getStats()`

返回已连接和已加载扩展的详细信息。

[[return-object-awaited]]
=== 返回对象（异步等待）：

* `loaded` String[]：已加载扩展的数组。
* `connected` String[]：已连接扩展的数组。这些扩展与主进程有活跃的基于 WebSocket 的 IPC 连接。

[source,javascript]
----
let stats = await Neutralino.extensions.getStats();
console.log('stats: ', stats);
----

